### ISSUE TITLE
Check if BigInt is necessary in Member struct

### ISSUE THREAD

**Issue by entropidelic** [lambdaclass/cairo-rs#497]
https://github.com/lambdaclass/cairo-rs/blob/ee50102d078a55b40c60e8822d9f5912e4e4f37f/src/serde/deserialize_program.rs#L73

I suspect a `Option<usize>` would be enough for the `offset` field, but it should be checked.

**Comment by azteca1998** [comment]
Looking at [the reference code](https://github.com/starkware-libs/cairo-lang/blob/54d7e92a703b3b5a1e07e9389608178129946efc/src/starkware/cairo/lang/compiler/preprocessor/struct_collector.py#L29-L78), an `usize` should be fine since it's computing address offsets and in `cairo-rs` those use `usize` too.
