### ISSUE TITLE
`cargo test` fails when run locally

### ISSUE THREAD

**Issue by tdelabro** [lambdaclass/cairo-rs#533]
```
failures:
    cairo_run::tests::cairo_run_custom_entry_point
    cairo_run::tests::run_with_no_trace
    cairo_run::tests::write_binary_memory_file
    cairo_run::tests::write_binary_trace_file
    cairo_run::tests::write_output_program

test result: FAILED. 604 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.27s
```

Those tests fail because they try to run files that do not exist such as
```
        let program_path = Path::new("cairo_programs/struct.json");
```
which is not compiled yet. `cairo_programs/struct.cairo` exist tho.

Running cargo tests on the main branch should always result in success.
If some tests require specific environments you can hide them behind `features` or use the `#[ignore]` attribute to ignore them until later

**Comment by fmoletta** [comment]
Hello! For many tests we run compiled cairo programs, and we chose to compile them before running the tests as opposed to having the compiled json files in the repo.
Our `test` target in the Makefile compiles these programs and runs cargo test, so `make test` should be used instead of running `cargo test`. This requires you to have cairo-lang installed (We are currently using version 0.9.1 as we haven't updated our test programs with the new syntax).
Hope this is useful!

**Comment by tdelabro** [comment]
It is indeed really usefull. And it was mentioned in the README. Sorry for not looking back to it.
